name: ShareIt API Tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install postgresql-client
        run: sudo apt-get install -y postgresql-client

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      # Здесь добавьте шаги для запуска ваших тестов, например:
      # - name: Run tests
      #   run: ./gradlew test

  build:
    uses: yandex-praktikum/java-shareit/.github/workflows/api-tests.yml@ci